export const GET_RECEPCIONISTAS = "GET_RECEPCIONISTAS";

export const ADD_RECEPCIONISTA = "ADD_RECEPCIONISTA";

export const ELIMINAR_RECEPCIONISTA = "ELMINAR_RECEPCIONISTA";

export const ELIMINAR_RECEPCIONISTA_ERROR = "ELMINAR_RECEPCIONISTA_ERROR";

export const EDIT_RECEPCIONISTA = "EDIT_RECEPCIONISTA";
