export const ADD_RESERVA = "ADD_RESERVA";
export const ADD_RESERVA_SUCCESS = "ADD_RESERVA_SUCCESS";
export const ADD_RESERVA_ERROR = "ADD_RESERVA_ERROR";

export const EDIT_RESERVA = "EDIT_RESERVA";
export const EDIT_RESERVA_SUCCESS = "EDIT_RESERVA_SUCCESS";
export const EDIT_RESERVA_ERROR = "EDIT_RESERVA_ERROR";

export const DELETE_RESERVA = "DELETE_RESERVA";
export const DELETE_RESERVA_SUCCESS = "DELETE_RESERVA_SUCCESS";
export const DELETE_RESERVA_ERROR = "DELETE_RESERVA_ERROR";

export const GET_RESERVA = "GET_RESERVA";
export const GET_RESERVA_SUCCESS = "GET_RESERVA_SUCCESS";
export const GET_RESERVA_ERROR = "GET_RESERVA_ERROR";

export const GET_RESERVAS = "GET_RESERVAS";
export const GET_RESERVAS_SUCCESS = "GET_RESERVAS_SUCCESS";
export const GET_RESERVAS_ERROR = "GET_RESERVAS_ERROR";
